# Makefile for the focaltech touchscreen ft3418 I2C drivers.

obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_test/

obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_flash/

obj-$(CONFIG_TOUCHSCREEN_FT3418_I2C)	+=  focaltech_i2c.o
